spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: chayan@1401


mvc:
  pathmatch:
    matching-strategy: ANT_PATH_MATCHER

#JPA settings
  jpa.hibernate.ddl_auto: create